export const CATEGORIES = [
  { id: "everyday", label: "Everyday" },
  { id: "convert", label: "Converters" },
  { id: "money", label: "Money" },
  { id: "home", label: "Home & DIY" },
  { id: "health", label: "Health" },
  { id: "creative", label: "Creative" },
  { id: "smart", label: "Smart Input" },
];

export const CALCULATORS = [
  { id: "standard", category: "everyday", title: "Standard", blurb: "Do basic math with large buttons and a clear display." },
  { id: "tape", category: "everyday", title: "Living Tape", blurb: "A scrolling history you can tap to fix. The whole list updates." },
  { id: "scientific", category: "everyday", title: "Scientific", blurb: "Trigonometry, logarithms, exponents, and constants." },
  { id: "graphing", category: "everyday", title: "Graphing", blurb: "Type a formula and draw the curve. Zoom and tap points." },
  { id: "programmer", category: "everyday", title: "Programmer", blurb: "Convert binary, hexadecimal, octal, and decimal." },
  { id: "statistics", category: "everyday", title: "Statistics", blurb: "Mean, median, and standard deviation for a list of numbers." },
  { id: "units", category: "convert", title: "Unit Converter", blurb: "Length, weight, temperature, and speed." },
  { id: "currency", category: "convert", title: "Currency Converter", blurb: "Live exchange rates for USD, EUR, and more." },
  { id: "datetime", category: "convert", title: "Date & Time", blurb: "Days between dates, or a date 90 days from now." },
  { id: "cooking", category: "convert", title: "Cooking", blurb: "Kitchen units, flour cups to grams, oven temperatures." },
  { id: "jewelry", category: "convert", title: "Jewelry", blurb: "Ring size converter across US, UK, EU, and JP." },
  { id: "tip", category: "money", title: "Tip & Split", blurb: "Restaurant tip and an even split among friends." },
  { id: "loan", category: "money", title: "Loan & Mortgage", blurb: "Monthly payment including tax and insurance." },
  { id: "extra", category: "money", title: "Extra Payment", blurb: "See time and interest saved with extra monthly payments." },
  { id: "compound", category: "money", title: "Compound Interest", blurb: "Watch savings grow, with an inflation-adjusted real value." },
  { id: "salary", category: "money", title: "Salary & Tax", blurb: "Hourly to salary and estimated take-home after tax." },
  { id: "auto", category: "money", title: "Auto Loan & EV", blurb: "Compare a gas car to an EV, including fuel and charging." },
  { id: "profit", category: "money", title: "Business Profit", blurb: "Margin and markup so you can price for a profit." },
  { id: "betting", category: "money", title: "Sports Betting", blurb: "American, decimal, and fractional odds with implied probability." },
  { id: "flooring", category: "home", title: "Flooring & Tile", blurb: "Boxes of tile or laminate, plus 10% waste." },
  { id: "paint", category: "home", title: "Paint Estimator", blurb: "Gallons needed after subtracting doors and windows." },
  { id: "concrete", category: "home", title: "Concrete & Bricks", blurb: "Bags of concrete or bricks for a patio or wall." },
  { id: "roofing", category: "home", title: "Roofing", blurb: "Roof area and shingle bundles from pitch." },
  { id: "carpet", category: "home", title: "Carpet", blurb: "Rolls for irregular rooms made of rectangles." },
  { id: "bmi", category: "health", title: "BMI", blurb: "A quick check of weight range for your height." },
  { id: "bodyfat", category: "health", title: "Body Fat", blurb: "Navy-method estimate from waist, neck, and hip." },
  { id: "tdee", category: "health", title: "Calorie Counter", blurb: "Daily calories to maintain, lose, or gain weight." },
  { id: "water", category: "health", title: "Water Intake", blurb: "Daily water from body weight and activity." },
  { id: "pregnancy", category: "health", title: "Pregnancy Due Date", blurb: "Due date from the first day of the last period." },
  { id: "photo", category: "creative", title: "Photography", blurb: "Depth of field and exposure time from your settings." },
  { id: "music", category: "creative", title: "Music Production", blurb: "Convert BPM into delay and reverb times." },
  { id: "camera", category: "smart", title: "Camera Math", blurb: "Photograph a problem, then solve it step by step." },
  { id: "receipt", category: "smart", title: "Receipt Scanner", blurb: "Turn a grocery receipt into a digital list you can split." },
  { id: "handwriting", category: "smart", title: "Handwriting", blurb: "Draw digits on the screen and solve the math." },
];
